version: '3.8'

services:
  caddy:
    image: caddy:2-alpine
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web

  stepperslife:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_CONVEX_URL=https://youthful-porcupine-760.convex.cloud
        - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_live_Y2xlcmsuc3RlcHBlcnNsaWZlLmNvbSQ
        - NEXT_PUBLIC_APP_URL=https://stepperslife.com
    container_name: stepperslife-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PLATFORM_FEE_PER_TICKET: 1.50
      # Clerk Auth
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_live_Y2xlcmsuc3RlcHBlcnNsaWZlLmNvbSQ
      CLERK_SECRET_KEY: sk_live_Zw4hG4urkym6QmEGc5DpZ2EijZebajzmWhfuYx4itq
      # Convex
      NEXT_PUBLIC_CONVEX_URL: https://youthful-porcupine-760.convex.cloud
      CONVEX_DEPLOYMENT: prod:youthful-porcupine-760
      # App Config
      NEXT_PUBLIC_APP_URL: https://stepperslife.com
      NEXT_PUBLIC_APP_NAME: SteppersLife
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: AIzaSyAD1jQHxD0Y7TfZzv8D8V7o7DfwB7CjJxE
      DATABASE_URL: "file:./dev.db"
    networks:
      - web
    labels:
      - "caddy=stepperslife.com"

  # Optional: N8N Workflow Automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-automation
    restart: unless-stopped
    environment:
      - N8N_HOST=n8n.agistaffers.com
      - N8N_PROTOCOL=https
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n.agistaffers.com
      - GENERIC_TIMEZONE=America/New_York
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - web

  # Optional: Open WebUI for Ollama
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: unless-stopped
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    volumes:
      - open_webui_data:/app/backend/data
    networks:
      - web
    depends_on:
      - ollama

  # Optional: Ollama
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - web

  # Optional: Flowise AI Agent Builder
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    environment:
      - PORT=3002
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin
      - DATABASE_PATH=/root/.flowise
    volumes:
      - flowise_data:/root/.flowise
    networks:
      - web

volumes:
  caddy_data:
  caddy_config:
  n8n_data:
  open_webui_data:
  ollama_data:
  flowise_data:

networks:
  web:
    external: false