#!/bin/bash

# Manual fix to run immediately
echo "Copy and run this command:"
echo ""
echo "ssh root@72.60.28.175 << 'EOF'"
echo "docker ps | grep stepperslife"
echo "docker stop stepperslife-prod 2>/dev/null || true"
echo "docker rm stepperslife-prod 2>/dev/null || true"
echo ""
echo "# If image exists, run it directly"
echo "if docker images | grep -q stepperslife; then"
echo "  docker run -d \\"
echo "    --name stepperslife-prod \\"
echo "    --restart unless-stopped \\"
echo "    --network coolify \\"
echo "    -p 3000:3000 \\"
echo "    -e NODE_ENV=production \\"
echo "    -e PLATFORM_FEE_PER_TICKET=1.50 \\"
echo "    -e NEXTAUTH_URL=https://stepperslife.com \\"
echo "    -e NEXTAUTH_SECRET=MNPqnyyK7CDiaLwgHQEj+cpt0miM03ff0ECPxl5VKdc= \\"
echo "    -e GOOGLE_CLIENT_ID=1009301533734-s9lbcqhrhehvtmd2bbrpkuvf4oo7ov3v.apps.googleusercontent.com \\"
echo "    -e GOOGLE_CLIENT_SECRET=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 \\"
echo "    -e NEXT_PUBLIC_CONVEX_URL=https://mild-newt-621.convex.cloud \\"
echo "    -e CONVEX_DEPLOYMENT=prod:mild-newt-621 \\"
echo "    -e NEXT_PUBLIC_APP_URL=https://stepperslife.com \\"
echo "    -e NEXT_PUBLIC_APP_NAME=SteppersLife \\"
echo "    -e NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=AIzaSyAD1jQHxD0Y7TfZzv8D8V7o7DfwB7CjJxE \\"
echo "    -e DATABASE_URL=\"file:./dev.db\" \\"
echo "    --label \"traefik.enable=true\" \\"
echo "    --label \"traefik.http.routers.stepperslife.rule=Host(\\\`stepperslife.com\\\`)\" \\"
echo "    --label \"traefik.http.services.stepperslife.loadbalancer.server.port=3000\" \\"
echo "    stepperslife:latest"
echo "else"
echo "  echo 'No image found. GitHub Actions may still be building...'"
echo "fi"
echo ""
echo "# Check status"
echo "sleep 5"
echo "docker ps | grep stepperslife"
echo "curl -s http://localhost:3000/api/auth/providers | jq '.providers.google'"
echo "EOF"